---
abstract: 'Teeny-weeny templating system'
author:
  - 'Scott McWhirter <konobi@cpan.org>'
build_requires:
  IO::Scalar: 0
  Test::Deep: 0
  Test::Differences: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Teeny
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Moose: 0.57
version: 0.00_001
resources:
  repository: http://github.com/konobi/template-teeny/
